mybatis:
     mapper-locations: "classpath:/mybatis/mapper/**.xml"
     config-location: "classpath:mybatis-config.xml"
spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 100
      max-idle: 100
      min-idle: 0
      max-wait: 10000
server:
  port: 80



